services:
  app:
    build:
      context: .
      dockerfile: gdvi/app.Dockerfile
  docs:
    build:
      context: docs
    volumes:
      - "./docs:/build"
    ports:
      - "8000:8000"
    command: "mkdocs serve --dev-addr 0.0.0.0:8000 --config-file /build/mkdocs.yml"
