services:
#  app:
#    build:
#      context: .
#      dockerfile: gd6/app.Dockerfile
  docs:
    build:
      context: docs
    volumes:
      - "./docs:/build"
    ports:
      - "8000:8000"
    entrypoint: 
      - "mkdocs"
    command: "serve --dev-addr 0.0.0.0:8000 --config-file /build/mkdocs.yml"
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"