services:
  docs:
    build:
      context: docs
    volumes:
      - "./docs:/build"
    ports:
      - "8000:8000"
    entrypoint: 
      - "mkdocs"
    command: "serve --dev-addr 0.0.0.0:8000 --config-file /build/mkdocs.yml"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    volumes:
      - "./files:/files"
    ports:
      - "8080:8080"
  gdl:
    build:
      context: .
      dockerfile: gdl.Dockerfile
    volumes:
      - "./files:/files"
